#!/usr/bin/env ruby
require 'fileutils'
require 'hamidashi'
require 'pdf/reader'
require 'tmpdir'

if ARGV.empty?
  puts 'Usage: hamidashi example.pdf'
  exit 1
end

pdf_path   = File.expand_path(ARGV[0])
output_dir = File.expand_path("hamidashi-#{Time.now.strftime("%Y%m%d%H%M%S")}")

Dir.mktmpdir('hamidashi') do |temp_dir|
  hamidashi = Hamidashi.new

  (0...PDF::Reader.new(pdf_path).page_count).each do |page|
    if hamidashi.overflow?(pdf_path, page)
      puts page
      hamidashi.save_page(pdf_path, page, "#{temp_dir}/#{page}.png")
    end
  end

  unless Dir.glob(File.join(temp_dir, '*.png')).empty?
    FileUtils.cp_r(temp_dir, output_dir)
    exit 1
  end
end
